SELECT
  TRIM(SL.SLITEM) AS ITEM_NUMBER,
  SL.SLDATE       AS SALES_DATE,
  SUM(SL.SLBLUS)  AS SALES_SF
FROM GSFL2K.SALELINE SL
WHERE SL.SLDATE >= '{hist_start_date}'
  AND SL.SLDATE <  '{hist_end_date_exclusive}'
  AND TRIM(SL.SLITEM) IN ({sku_list})
GROUP BY TRIM(SL.SLITEM), SL.SLDATE
ORDER BY TRIM(SL.SLITEM), SL.SLDATE
