SELECT
  TRIM(L.SLITEM) AS ITEM_NUMBER,
  H.SHIDAT       AS SALES_DATE,
  SUM(COALESCE(L.SLBLUO,0)) AS QTY_SOLD_SF
FROM GSFL2K.SHLINE L
JOIN GSFL2K.SHHEAD H
  ON H.SHCO   = L.SLCO
 AND H.SHLOC  = L.SLLOC
 AND H.SHORD# = L.SLORD#
WHERE L.SLUM2 LIKE '%SF%'
  AND H.SHIDAT >= ?
  AND H.SHIDAT <  ?
GROUP BY
  TRIM(L.SLITEM),
  H.SHIDAT
ORDER BY
  TRIM(L.SLITEM),
  H.SHIDAT
